dist: trusty
language: node_js

cache:
  directories:
  - node_modules

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      node_js: 8
      env: TEST_SUITE=osx
    - os: osx
      node_js: 10
      env: TEST_SUITE=osx
    - os: osx
      node_js: 11
      env: TEST_SUITE=osx
    - os: linux
      node_js: 8
      env: TEST_SUITE=linux
    - os: linux
      node_js: 10
      env: TEST_SUITE=linux
    - os: linux
      node_js: 11
      env: TEST_SUITE=linux

before_install:
 - 'if [ $TEST_SUITE = "linux" ]; then sudo apt-get update && sudo apt-get install -y autoconf libtool pkg-config nasm build-essential; fi'
 - 'if [ $TEST_SUITE = "osx" ]; then sudo brew install libpng; fi'

script: npm run travis:test
